name = "BET"

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false
defaultTargets = ["BET"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "BET"
